### ISSUE TITLE
AWS Endpoint Not Resolvable

### ISSUE THREAD

**Issue by mfansler** [loosolab/cardiac-progenitors#1]
The AWS endpoint specified in the `original_analysis/README.md`:

```
Sys.setenv("AWS_S3_ENDPOINT" = "mpi-bn.mpg.de",
           "AWS_DEFAULT_REGION" = "s3")
```
is not resolvable, i.e., it throws the error:

> Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: mpi-bn.mpg.de

What is the correct host to use to obtain the data?

**Comment by jenzopr** [comment]
Hi Mervin,

thats weird. The AWS endpoint should be `s3.mpi-bn.mpg.de`. I had to add the `s3` as `AWS_DEFAULT_REGION` to hack an issue in cloudyr/aws.s3. Let me check that on my side and come back to you.

In the meantime, can you reach `https://s3.mpi-bn.mpg.de/` from your browser?

Best,
Jens

**Comment by jenzopr** [comment]
Hi Mervin,

changing the `AWS_S3_ENDPOINT` to `s3.mpi-bn.mpg.de` and leaving `AWS_DEFAULT_REGION` blank resolves the issue. I updated the README accordingly.

Best,
Jens

**Comment by jenzopr** [comment]
Package version was `0.3.12.1` from [CRAN](https://cran.r-project.org/web/packages/aws.s3/index.html).
