### ISSUE TITLE
Missing src/DE.R file?

### ISSUE THREAD

**Issue by WilliamSalvidge** [loosolab/cardiac-progenitors#3]
Hey, 

I'm just trying to re-run your SOM clustering script in cardiac-progenitors/src/04_clustering.R, as I might try and apply the same technique to my single cell data.

However in the R script it specifies a file source ("src/DE.R") which doesn't seem to exist in the cardiac-progenitors/src folder. Is this meant to be there but is missing or have I made an error in sourcing this file. 

Thanks for any help,

Will

**Comment by jenzopr** [comment]
Dear Will,
per be400aa, I added the routines for DE analysis. Hope this helps!

Best,
Jens
