### ISSUE TITLE
source code for Figures 2a-b

### ISSUE THREAD

**Issue by friedue** [loosolab/cardiac-progenitors#4]
Hi,

thanks for documenting your analysis so comprehensively, it's quite impressive! I was just wondering where the documentation for the trajectory images of Figures 2a and b are?

Cheers,

Friederike

**Comment by jenzopr** [comment]
Hi Frederike,

thanks a lot for your interest and the nice words. Indeed, source code for Figure 2a and b seem to be missing. I can put them into a script and add them to the repository in the next days, in case you really need them.

Basically, those are just scatter plots of two diffusion components (available in `pData(c1_subset)$dm1` and `pData(c1_subset)$dm2`) coloured by either *dpt* (`pData(c1_subset)$dpt`) or *cluster* (`pData(c1_subset)$cluster`). For 2a, we only used Nkx2-5+ cells, for 2b only Isl1+ cells :-)

Let me know if you need further assistance,
Jens

**Comment by friedue** [comment]
Hi Jens,

thanks for the quick reply. I was mostly interested to see how you decided to draw the paths/arrows.

**Comment by jenzopr** [comment]
The arrows were drawn by hand afterwards 😀

**Comment by friedue** [comment]
Aha! :)

**Comment by friedue** [comment]
So, how did you know which direction to put the arrow? I.e., why not go the opposite direction?

**Comment by jenzopr** [comment]
Sorry to have no positive answer here. However, I can imagine that an overlay with the density estimate (which should be high in areas of the cells) could help for the path. The direction and position of the arrowhead needs expert knowledge. In our case, we had additional information from the embryonic timepoint and *guessed* (educated, of course) that the trajectory starts with cells from the early timepoint (E7.5).

**Comment by friedue** [comment]
That's actually helpful insights -- I guessed it was done that way, just wanted to make sure I had guessed right :)
