### ISSUE TITLE
error with boot.ic 

### ISSUE THREAD

**Issue by airichli** [loosolab/cardiac-progenitors#6]
Hi, I get an error when running Figure_2cd.R. 

`nkx_ic_df <- as.data.frame(boot.ic(nkx_data, groups = nkx_cluster, R = 1000, n = 30, p.val = 0.05))
Error in boot.ic(nkx_data, groups = nkx_cluster, R = 1000, n = 30, p.val = 0.05) : 
  could not find function "boot.ic"`

Is there any other package that needed to be installed? Thank you.

**Comment by jenzopr** [comment]
Dear airichli,

you're absolutely right - the `boot.ic` function has been replaced by `singlecellutils::bootstrap_transition_index`, which currently works only for a `SingleCellExperiment` object. For your reference, I pasted the original function below.

Best,
Jens

```
boot.ic <- function(data, groups, n = 20, R = 999, ...) {
  if (!is.factor(groups)) {
    groups <- factor(groups)
  }
  b.ic <- lapply(levels(groups), function(g) {
    d <- data[, groups == g]
    boot::boot(d, function(x, p.val) computeIC(x, p.val)$ic, sim="parametric", R=R, ran.gen = boot_subsample, mle=n, ...)
  })

  ic_values <- sapply(b.ic, function(l) l$t)
  colnames(ic_values) <- levels(groups)
  return(ic_values)
}```

**Comment by airichli** [comment]
Thank you very much!
