### ISSUE TITLE
problem with heterogeneity.R

### ISSUE THREAD

**Issue by airichli** [loosolab/cardiac-progenitors#7]
Dear Jen,

I also met a problem in heterogeneity.R. I could not find the function dropout.fun and cv2.fun in line 57 and 64. Could you please check this? Thank you!

Best wishes,
Aifu.

**Comment by jenzopr** [comment]
Same issue - the functions have been replaced.

```
cv2.fun <- function(x) {
  x <- x[!is.na(x)]
  if (mean(x) == 0) {
    return(0)
  }
  stats::var(x) / mean(x)^2
}
```

```
dropout.fun <- function(x, limit=0) {
  x <- x[!is.na(x)]
  sum(x<=limit)/length(x)
}
```

**Comment by airichli** [comment]
Got it. Thanks Jens.
